spring.application.name=gateway-server
spring.profiles.active=local
server.port=5000

# ========================
# Spring Cloud Gateway
# ========================
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Routes - CLINIC
spring.cloud.gateway.server.webflux.routes[0].id=CLINIC-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CLINIC-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/clinics/**,/api/clinics/**,/api/admin/clinics/**

# Routes - USER
spring.cloud.gateway.server.webflux.routes[1].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**,/api/admin/users/**,/api/users/**, /users/**

# Routes - SERVICE-OFFER
spring.cloud.gateway.server.webflux.routes[2].id=OFFER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://OFFER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/service-offering/**

# Routes - CATEGORY
spring.cloud.gateway.server.webflux.routes[3].id=CATEGORY-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/categories/**

# Routes - BOOKING
spring.cloud.gateway.server.webflux.routes[4].id=BOOKING-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/bookings/**

# Routes - PAYMENT
spring.cloud.gateway.server.webflux.routes[5].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payments/**

# Routes - NOTIFICATION
spring.cloud.gateway.server.webflux.routes[6].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[6].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications/**

# Routes - REVIEW
spring.cloud.gateway.server.webflux.routes[7].id=REVIEW-SERVICE
spring.cloud.gateway.server.webflux.routes[7].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/reviews/**

# Default Filters
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# ========================
# CORS
# ========================
# Thêm port 5173 vào danh sách allowedOrigins
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:3173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[2]=https://clinic-booking-three.vercel.app

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# ========================
# Security (OAuth2 Resource Server)
# ========================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7080/realms/clinic-booking/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/clinic-booking
# ========================
# Actuator
# ========================
management.endpoints.web.exposure.include=prometheus,health,info
management.health.readiness-state.enabled=true
management.health.liveness-state.enabled=true
management.endpoint.shutdown.access=read_only
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.endpoint.env.access=read_only

#Sleuth,Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ========================
# Eureka
# ========================
eureka.instance.preferIpAddress=true
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/

# ========================
# Info
# ========================
info.app.name=Gateway server
info.app.description=Gateway server for ecommerce website