spring.application.name=review-service
spring.profiles.active=local
# ===============================
# SERVER
# ===============================
server.port=5008

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/review_db?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# MAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=prometheus,health,info
management.health.readiness-state.enabled=true
management.health.liveness-state.enabled=true
management.endpoint.shutdown.access=read_only
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

#Sleuth,Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ===============================
# EUREKA
# ===============================
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/clinic-booking

# ===============================
# INFO
# ===============================
info.app.name=Review Service
info.app.description=Review API For Clinic Booking System
info.app.version=1.0.0